---

- name: Provision
  hosts: all
  tasks:

    - name: Update cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        force_apt_get: true
      become: true

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: true
      become: true

    - name: Add a new user 
      user:
        name: nimeshjm
        shell: /bin/bash
        password: "onetimepasswordthatwillneverbeused"
      become: true

    - name: Add user to sudoers
      copy:
        dest: "/etc/sudoers.d/nimeshjm"
        content: "nimeshjm  ALL=(ALL)  NOPASSWD: ALL"
      become: true

    - name: Deploy SSH Key
      authorized_key: 
        user: nimeshjm
        key: "{{ lookup('file', 'id_rsa.pub') }}"
        state: present
      become: true

    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      become: true
        
    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      become: true
      notify:
        - restart ssh

    - name: Create secondary storage
      become: true
      lvg:
        vg: BIGDISK
        pvs: /dev/vdb
    
    - name: Size secondary storage
      become: true
      lvol:
        vg: BIGDISK
        lv: "BIGDISK"
        size: 999G

    - name: Create file system
      become: true
      filesystem:
        fstype: ext4
        dev: /dev/BIGDISK/BIGDISK
    
    - name: Mount logical volume
      become: true
      mount:
        name: /mnt/storage
        src: /dev/BIGDISK/BIGDISK
        fstype: ext4
        state: mounted  
            
    - name: Install dependencies
      become: true
      apt:
        state: latest
        name: "{{item}}"
      with_items:
        - apt-transport-https   
        - ca-certificates 
        - curl 
        - gnupg-agent 
        - software-properties-common

    - name: Add docker apt-key
      become: true
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 

    - name: Add docker apt repository
      become: true
      apt_repository: 
        repo: 'deb https://download.docker.com/linux/ubuntu xenial stable' 
        state: present 
        filename: docker
        update_cache: yes

    - name: Install docker
      become: true
      apt:
        state: latest
        name: "{{item}}"
      with_items:
        - docker-ce 
        - docker-ce-cli
        - containerd.io

    - name: Setup docker in secondary storage
      become: true
      copy:
        content: '{"data-root":"/mnt/storage/docker"}'
        dest: /etc/docker/daemon.json
      notify:
        - restart docker
    
    - name: Add users to docker group
      user:
        name: "nimeshjm"
        append: yes
        groups: docker
      become: true
        
    - name: Install docker compose
      become: true
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0777'
        checksum: sha256:cfb3439956216b1248308141f7193776fcf4b9c9b49cbbe2fb07885678e2bb8a

    - name: Done
      debug:
        msg: "done"

  handlers:
    - name: restart ssh
      become: true
      service:
        name=sshd
        state=restarted

    - name: restart docker
      become: true
      service:
        name=docker
        state=restarted

          
